Update chromatic-comment.yml

diff --git a/.github/workflows/chromatic-comment.yml b/.github/workflows/chromatic-comment.yml
--- a/.github/workflows/chromatic-comment.yml
+++ b/.github/workflows/chromatic-comment.yml
@@ -63,8 +63,11 @@ jobs:
         yarn chromatic > chromatic.log
         BUILD_URL=$(cat chromatic.log | sed -n 's#.*View build details at \(.*\)#\1#p' | head -n 1)
         STORYBOOK_URL=$(cat chromatic.log | sed -n 's#.*View your Storybook at \(.*\)#\1#p' | head -n 1)
+        ERROR_URL=$(cat chromatic.log | sed -n 's#.*visual changes: Review the changes at \(.*\)#\1#p' | head -n 1)
         echo "::set-output name=target_url::$STORYBOOK_URL"
         echo "::set-output name=log_url::$BUILD_URL"
+        echo "::set-output name=error_url::$ERROR_URL"
+        if [["$ERROR_URL"]] ; then exit 1; fi
     - name: POST new status to the Github API (success)
       run: |
           echo "${{steps.chr.outputs.target_url}} - ${{steps.chr.outputs.log_url}}"
@@ -89,6 +92,6 @@ jobs:
             "state": "failure",
             "context": "Chromatic",
             "description": "Chromatic failed",
-            "target_url":"${steps.chromatic.outputs.log_url}"
+            "target_url":"https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
             }' 
 
